=== T-MAPY/GenSMD/model/genmodel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="genmodel" xmlns="http://gensmd.local/genmodel"
	targetNamespace="http://gensmd.local/genmodel" xmlns:tns="http://gensmd.local/genmodel"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GenModel">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SelectorList">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Selector" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ElementType" type="ElementTypeDefinition" minOccurs="0" maxOccurs="1" />
										<xs:element name="RelationList" minOccurs="0"	maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
			                    <xs:element name="RelationSelector" minOccurs="0" maxOccurs="unbounded">
			                      <xs:complexType>
			                        <xs:sequence>
																<xs:element name="Relation" maxOccurs="1">
										              <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="Footprint" minOccurs="0" type="FootprintDefinition" />
                                    </xs:sequence>
			                              <xs:attribute name="clearance" type="xs:float" />
			                              <xs:attribute name="conflict" type="BoolDefinition" />
										              </xs:complexType>
																</xs:element>
														  </xs:sequence>
			                        <xs:attribute name="cond"	use="optional">
			                        	<xs:simpleType>
			                        		<xs:restriction base="xs:string">
			                        			<xs:minLength value="1" />
			                        		</xs:restriction>
			                        	</xs:simpleType>
			                        </xs:attribute>
			                        <xs:attribute name="join" use="optional">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:minLength value="1" />
                                  </xs:restriction>
                                </xs:simpleType>
			                        </xs:attribute>
														</xs:complexType>
												  </xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="cond" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ElementTypeList">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="ElementType" type="ElementTypeDefinition" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="ElementTypeDefinition">
		<xs:sequence>
      <xs:element name="TagDict" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Tag" minOccurs="0" maxOccurs="unbounded">
	            <xs:complexType>
	              <xs:attribute name="key" type="xs:string" use="required" />
	              <xs:attribute name="value" type="xs:string" use="required" />
	            </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
			<xs:element name="TagList" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Tag" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Footprint" minOccurs="0" type="FootprintDefinition" />
		</xs:sequence>
		<xs:attribute name="id" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="20"></xs:maxLength>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="geomType" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="point"></xs:enumeration>
					<xs:enumeration value="line"></xs:enumeration>
					<xs:enumeration value="polygon"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
    <xs:attribute name="priority" type="xs:int" use="optional" />
    <xs:attribute name="topology"  type="BoolDefinition" use="optional" />
	</xs:complexType>
	
  <xs:complexType name="FootprintDefinition">
    <xs:sequence>
      <xs:element name="Geometry" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Wkt" minOccurs="1" type="xs:string" />
            <xs:element name="Origin">
              <xs:complexType>
                <xs:attribute name="x" type="xs:float" use="optional" />
                <xs:attribute name="y" type="xs:float" use="optional" />
              </xs:complexType>
            </xs:element>  
          </xs:sequence>
        </xs:complexType>
      </xs:element>  
      <xs:element name="Buffer" minOccurs="0">
        <xs:complexType>
          <xs:attribute name="radius" type="xs:float" use="optional" />
          <xs:attribute name="cap" use="optional" type="CapDefinition" />
          <xs:attribute name="capStart" use="optional" type="CapDefinition" />
          <xs:attribute name="capEnd" use="optional" type="CapDefinition" />
          <xs:attribute name="offset" type="xs:float" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
	
	
	<xs:simpleType name="CapDefinition">
		<xs:restriction base="xs:string">
			<xs:enumeration value="round"></xs:enumeration>
			<xs:enumeration value="flat"></xs:enumeration>
			<xs:enumeration value="square"></xs:enumeration>
      <xs:enumeration value="triangle"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
  <xs:simpleType name="BoolDefinition">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true" />
      <xs:enumeration value="false" />
    </xs:restriction>
  </xs:simpleType>
	
</xs:schema>

=== T-MAPY/GenSMD/model/prototype.xml
<?xml version="1.0" encoding="UTF-8"?>
<gen:GenModel xmlns:gen="http://gensmd.local/genmodel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gensmd.local/genmodel genmodel.xsd">
<SelectorList>
  <Selector>
    <ElementType geomType="line" />
    <RelationList>
      <RelationSelector>
        <Relation conflict="true" />
      </RelationSelector>
      <RelationSelector join="selector.tagdict->>'color' = relation.tagdict->>'color'">
        <Relation clearence="1.2" />
      </RelationSelector>
    </RelationList>  
  </Selector>
  <Selector cond="taglist ? 'komunikace'">
    <ElementType priority="1" topology="true" />
  </Selector>
  <Selector cond="taglist ? 'hranice'">
    <ElementType priority="4" topology="true" />
  </Selector>
  <Selector cond="taglist ? 'voda'">
    <ElementType priority="2" />
  </Selector>
  <Selector cond="taglist ? 'voda' AND geomtype = 'line'">
    <ElementType topology="true" />
  </Selector>
  <Selector cond="taglist ? 'zelen'">
    <ElementType priority="6" />
  </Selector>
  <Selector cond="taglist ? 'terenni stupen'">
    <ElementType priority="5" />
  </Selector>
  <Selector cond="id = '4120000'">
    <RelationList>
      <RelationSelector cond="id = '6060100'">
        <Relation>
			    <Footprint>
			      <Buffer radius="0.7" cap="flat" offset="-0.45" />
			    </Footprint>        
        </Relation>
      </RelationSelector>
    </RelationList>  
  </Selector>
  <Selector cond="geomtype = 'polygon'">
    <RelationList>
      <RelationSelector>
        <Relation conflict="false" clearence="0" />
      </RelationSelector>
    </RelationList>  
  </Selector>
</SelectorList>
<ElementTypeList>

  <ElementType id="1720000">
    <TagDict>
      <Tag key="color" value="gray" />
    </TagDict>
    <Footprint>
      <Buffer radius="0.2" />
    </Footprint>
  </ElementType>
  
  <ElementType id="2470000">
    <TagDict>
      <Tag key="color" value="gray" />
    </TagDict>
    <TagList>
      <Tag>komunikace</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="1" />
    </Footprint>
  </ElementType>
  
  <ElementType id="2480001">
    <TagDict>
      <Tag key="color" value="gray" />
    </TagDict>
    <TagList>
      <Tag>komunikace</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="1" />
    </Footprint>
  </ElementType>
  
  <ElementType id="2480006">
    <TagDict>
      <Tag key="color" value="gray" />
    </TagDict>
    <TagList>
      <Tag>komunikace</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="1" />
    </Footprint>
  </ElementType>
  
  <ElementType id="2490101">
    <TagDict>
      <Tag key="color" value="gray" />
    </TagDict>
    <TagList>
      <Tag>komunikace</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="0.75" />
    </Footprint>
  </ElementType>
  
  <ElementType id="2490200">
    <TagDict>
      <Tag key="color" value="gray" />
    </TagDict>
    <TagList>
      <Tag>komunikace</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="3" cap="flat" />
    </Footprint>
  </ElementType>
  
   
  <ElementType id="3020100">
    <TagDict>
      <Tag key="color" value="blue" />
    </TagDict>
    <TagList>
      <Tag>voda</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="0.75" />
    </Footprint>
  </ElementType>

  <ElementType id="3030000">
    <TagDict>
      <Tag key="color" value="blue" />
    </TagDict>
    <TagList>
      <Tag>voda</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="1.2" />
    </Footprint>
  </ElementType>

  <ElementType id="3040000">
    <TagDict>
      <Tag key="color" value="blue" />
    </TagDict>
    <TagList>
      <Tag>voda</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="1.2" />
    </Footprint>
  </ElementType>
     
  <ElementType id="3060000">
    <TagDict>
      <Tag key="color" value="blue" />
    </TagDict>
    <TagList>
      <Tag>voda</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="1.2" />
    </Footprint>
  </ElementType>
       
  <ElementType id="3330000" geomType="polygon">
    <TagDict>
      <Tag key="color" value="blue" />
    </TagDict>
    <TagList>
      <Tag>voda</Tag>
    </TagList>
  </ElementType>

  <ElementType id="4120000">
    <TagDict>
      <Tag key="color" value="green" />
    </TagDict>
    <TagList>
      <Tag>zelen</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="6" />
    </Footprint>
  </ElementType>
         
  <ElementType id="5210100">
    <TagDict>
      <Tag key="color" value="gray" />
    </TagDict>
    <TagList>
      <Tag>hranice</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="0.75" />
    </Footprint>
  </ElementType>
           
  <ElementType id="6060100">
    <TagDict>
      <Tag key="color" value="gray" />
    </TagDict>
    <TagList>
      <Tag>terenni stupen</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="3.75" cap="flat" offset="-3.5" />
    </Footprint>
  </ElementType>
             
</ElementTypeList>

</gen:GenModel>

=== T-MAPY/GenSMD/m1/model/zm10.xml
<?xml version="1.0" encoding="UTF-8"?>
<gen:GenModel xmlns:gen="http://gensmd.local/genmodel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gensmd.local/genmodel genmodel.xsd">
<SelectorList>
  <Selector cond="weight = 1">
    <ElementType geomType="line" weight="3" />
    <RelationList>
      <RelationSelector cond="false" join="">
        <Relation clearance="1.2" />
		    <Footprint>
		      <Geometry>
		        <Wkt>POLYGON(....)</Wkt>
		        <Origin x="0" y="1.0" />
		      </Geometry>
		      <Buffer radius="0.2" cap="flat" offset="1.1" />
		    </Footprint>
      </RelationSelector>
    </RelationList>
  </Selector>
  <Selector cond="true">
    <ElementType geomType="line" weight="3" />
    <RelationList>
      <RelationSelector cond="1=0" join="true">
        <Relation clearance="1.2" />
      </RelationSelector>
    </RelationList>
  </Selector>
</SelectorList>
<ElementTypeList>
  <ElementType id="1720000" geomType="line" weight="1">
    <TagDict>
      <Tag key="color" value="red" />
    </TagDict>
    <TagList>
      <Tag>silnice</Tag>
      <Tag>seda</Tag>
    </TagList>
    <Footprint>
      <Geometry>
        <Wkt>POLYGON(....)</Wkt>
        <Origin x="0" y="1.0" />
      </Geometry>
      <Buffer radius="0.2" cap="flat" offset="1.1" />
    </Footprint>
  </ElementType>
  <ElementType id="545454545" geomType="line" weight="1">
    <TagList>
      <Tag>topo</Tag>
      <Tag>silnice</Tag>
      <Tag>seda</Tag>
    </TagList>
    <Footprint>
      <Buffer radius="0.2" cap="flat" offset="1.1" />
    </Footprint>
  </ElementType>
</ElementTypeList>

</gen:GenModel>
